version: "3"  # 도커 컴포즈 버전
services:    # 이곳에 실행하려는 컨테이너들을 정의
  react:    # 컨테이너 이름
    build:   # 현 디렉토리에 있는 Dockerfile 사용
      context: .   # 도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
      dockerfile: Dockerfile.dev   # 도커파일 어떤것인지 지정
    ports:
      - "3000:3000"    # 포트 매핑
    volumes:   # 로컬 머신에 있는 파일들 맵핑
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true  # 리액트 앱을 끌 때 필요(버그수정)
  tests:   # 컨테이너 이름
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm","run","test"]
    environment:
      CHOKIDAR_USEPOLLING: "true"